### ISSUE TITLE
Duels Setup

### ISSUE THREAD

**Issue by mhiaxo** [valehq/changelog#4]
I have a beta version of the plugin on the server for 1.15.2. In the previous server, we had McDuels and it wasn't that great to use, but Duels wasn't working. I am _hoping_ after 8 months, it actually works. 

- [ ] Review Duels config.
- [ ] Setup Duels sign @ spawn.
![image](https://user-images.githubusercontent.com/61203966/77285578-b0d04980-6ca7-11ea-9a5c-8d90061795fa.png)
- [ ] Setup the Area, which is the area above the spawn.
![image](https://user-images.githubusercontent.com/61203966/77285595-bf1e6580-6ca7-11ea-803f-49bf7b9021d6.png)
- [ ] Hope this works!

**Comment by mhiaxo** [comment]
test

**Comment by mhiaxo** [comment]
This is partially done, not sure on what would be good prizes for winners (and losers)


```
    end-commands:
      # If set to 'true', the commands listed below will run at the end of a match.
      # default: false
      enabled: false

      # Available placeholders:
      # %winner% - Name of the winner of the match
      # %loser% - Name of the loser of the match
      commands:
      - give %winner% diamond 1
      - give %loser% poppy 1
      - flightcharge add %winner% 100
```
